trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(nodeVersion)
    displayName: 'Install Node.js'

  - script: npm install && npm install -g @angular/cli
    displayName: 'Install dependencies'

  - script: npm run build
    displayName: 'Compile TypeScript and Build'