- task: HelmDeploy@0
  displayName: Upgrade/install nginx-ingress
  inputs:
    azureSubscriptionEndpoint: 'myServiceConnection'
    azureResourceGroup: 'myRG'
    kubernetesCluster: 'myAKS'
    command: upgrade
    install: true
    chartType: Name
    chartName: nginx-stable/nginx-ingress
    releaseName: nginx
    namespace: nginx
    valueFile: nginx-affinity.yaml
    arguments: '--set replicaCount="2" --set loadBalancerIP="40.84.136.187" --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-internal"=\"true\" --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-internal-subnet"="mySubnet"'