version: '3.8'
services:
  # angular
  angular: # name of the first service
    build: # specify the directory of the Dockerfile
      context: ./angular.json
      dockerfile: Dockerfile1
    container_name: mean_angular
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - "4200:4200" # specify port forewarding
      - "49153:49153"
    environment:
      - NODE_ENV=dev
#node       
node:
    build:
      context: ./index.js
      dockerfile: Dockerfile1
      args:
        - NODE_VERSION=latest
        - PROJECT_PATH=/opt/app/
        - NODE_ENV=production
        - YARN=false
    volumes:
      - ../:/opt/app
    entrypoint: run-nodock "node index.js"
    tty: true
