version: '3.8'
services:
  # angular
  angular: # name of the first service
    build: # specify the directory of the Dockerfile
      context: ./angular
      dockerfile: Dockerfile1
    container_name: mean_angular
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - "4200:4200" # specify port forewarding
      - "49153:49153"
    environment:
      - NODE_ENV=dev
  # nginx
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile1
      args:
        - WEB_REVERSE_PROXY_PORT=8000
        - WEB_SSL=false
        - SELF_SIGNED=false
        - NO_DEFAULT=false
    volumes:
- ./nginx_file/node.gaurangacharya.co.conf /etc/nginx/sites_available/
- ./nginx_file/node.gaurangacharya.co.conf /etc/nginx/sites_enable/
- ./nginx_file/node.gaurangacharya.co.conf /etc/nginx/sites_available/
- ./nginx_file/node.gaurangacharya.co.conf /etc/nginx/sites_enable/
    ports:
      - "80:80"
      - "443:443"
    tty: true
  # node
  node:
    build:
      context: ./node
      dockerfile: Dockerfile1
      args:
        - NODE_VERSION=latest
        - PROJECT_PATH=/opt/app/
        - NODE_ENV=production
        - YARN=false
    volumes:
      - ../:/opt/app
    entrypoint: run-nodock "node index.js"
    tty: true
