version: '3'
dockerfile: Dockerfile1
services:
node:
build:
context: ./index.js
args:
- NODE_VERSION=latest
- PROJECT_PATH=/opt/app/
- NODE_ENV=production
- YARN=false
volumes:
- ../:/opt/app
entrypoint: run-nodock "node index.js"
tty: true

# Define the services/containers to be run
services:
angular: # name of the first service
build: # specify the directory of the Dockerfile
context: ./angular.json
container_name: mean_angular
ports:
- "4200:4200" # specify port forewarding
- "49153:49153"
environment:
- NODE_ENV=dev

nginx:
build: .
context:
- ./nginx_file/node.gaurangacharya.co.conf /etc/nginx/sites_available/
- ./nginx_file/node.gaurangacharya.co.conf /etc/nginx/sites_enable/
- ./nginx_file/node.gaurangacharya.co.conf /etc/nginx/sites_available/
- ./nginx_file/node.gaurangacharya.co.conf /etc/nginx/sites_enable/
args:
- WEB_REVERSE_PROXY_PORT=8000
- WEB_SSL=false
- SELF_SIGNED=false
- NO_DEFAULT=false
volumes:
- ./data/logs/nginx/:/var/log/nginx
- ./certbot/certs/:/var/certs
ports:
- "80:80"
- "443:443"
tty: true
