# apiVersion: networking.k8s.io/v1beta1
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: aks-frontend-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/server-alias: "dev.nextbillion.co"
spec:
  tls:
  - hosts:
    - dev.nextbillion.co # demo-aks-ingress.eastus.cloudapp.azure.com
    secretName: tls-secret
  rules:
  - host: dev.nextbillion.co # demo-aks-ingress.eastus.cloudapp.azure.com
    http:
      paths:
      - backend:
          serviceName: aks-frontend
          servicePort: 80
        path: /(.*)
      - backend:
          serviceName: user-mgmt-api-svc
          servicePort: 3501
        path: /user-management(/|$)(.*)
      - backend:
          serviceName: nextbillion-survey-api-svc
          servicePort: 7059
        path: /survey-api(/|$)(.*)
