trigger:
- main

pool:
vmImage: 'ubuntu-latest'
strategy:
matrix:
node_12_x:
node_version: 12.x
node_13_x:
node_version: 13.x

steps:
- task: NodeTool@0
inputs:
versionSpec: $(node_version)

- script: npm install
 npm install -g @angular/cli
    npm install
    ng build --prod
      displayName: 'npm install and build'



Build and deploy JavaScript and Node.js apps - Azure Pipelines
https://docs.microsoft.com
